# Generated by Django 4.2.11 on 2025-08-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailNo', models.CharField(max_length=10)),
                ('modelName', models.CharField(max_length=32)),
                ('manufacturer', models.CharField(max_length=32)),
                ('seatCapacity', models.IntegerField()),
                ('seatLayout', models.CharField(max_length=7)),
            ],
        ),
    ]
