# Generated by Django 4.2.11 on 2025-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNo', models.CharField(max_length=4)),
                ('travelClass', models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'FirstClass')], default='E', max_length=1)),
                ('isBooked', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
            ],
        ),
    ]
